### ISSUE TITLE
No python 2.7 pypi release

### ISSUE THREAD

**Issue by Koed00** [neithere/django-autoslug#3]
I was getting this setup.py error on version 0.9.1:

```python
    from _version_helper import __version__
    
ImportError: No module named _version_helper

```
Looking at  the releases I figure this was a packaging error that got fixed in 0.9.2. 
Unfortunately 0.9.2 is not available as a Python 2.7 package, just as a Py3 wheel.

**Comment by nicholasamorim** [comment]
I can confirm this issue.

**Comment by neithere** [comment]
Also reported in #1 — it's *not* fixed there, just more details.

Will fix in a couple of hours.

**Comment by neithere** [comment]
Fixed in 1.9.3.dev0.

**Comment by shaunbrady** [comment]
I'm still getting 1.9.1 with Python 2.7

root@excalibur:~# pip install django-autoslug
Downloading/unpacking django-autoslug
  Downloading django-autoslug-1.9.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/django-autoslug/setup.py) egg_info for package django-autoslug
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/django-autoslug/setup.py", line 18, in <module>
        from _version_helper import __version__
    ImportError: No module named _version_helper
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/django-autoslug/setup.py", line 18, in <module>

    from _version_helper import __version__

ImportError: No module named _version_helper

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/django-autoslug
Storing debug log for failure in /root/.pip/pip.log

**Comment by neithere** [comment]
Hmm, interesting, I saw the same behaviour but thought it was some local problem.

```
$ pip2.7 install django-autoslug --verbose
...
Found link https://pypi.python.org/packages/source/d/django-autoslug/django-autoslug-1.9.1.tar.gz#md5=8c45867310882e2bafdd263a9000cbf8 (from https://pypi.python.org/simple/django-autoslug/), version: 1.9.1
    Found link https://pypi.python.org/packages/source/d/django-autoslug/django-autoslug-1.9.3.dev0.tar.gz#md5=f8592dde18a9b8eb5c272f0093c53866 (from https://pypi.python.org/simple/django-autoslug/), version: 1.9.3.dev0
    Skipping link http://gnu.org/licenses/ (from https://pypi.python.org/simple/django-autoslug/); not a file
    Skipping link http://packages.python.org/django-autoslug/ (from https://pypi.python.org/simple/django-autoslug/); not a file
  Using version 1.9.1 (newest of versions: 1.9.1, 1.9.0, 1.8.0, 1.7.2, 1.7.1, 1.7.0, 1.6.1, 1.6.0, 1.5.0, 1.4.1, 1.4.0, 1.3.9, 1.3.8, 1.3.7, 1.3.6, 1.3.5, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.1, 1.2.0, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.1)
...
```
So it sees the dev version but doesn't even include it in comparison, perhaps because it's `*dev`.

Okay, will release a non-dev version...

**Comment by shaunbrady** [comment]
Yep, works for me.  Thanks.
